services:
  invest:
    container_name: invest
    restart: unless-stopped
    build: .
    networks:
      - proxy
#    ports:
#      - "8000:8000"
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invest.rule=Host(`invest.theroeders.net`)"
      - "traefik.http.services.invest.loadbalancer.server.port=8000"
      - "traefik.http.routers.invest.entrypoints=https"
      - "traefik.http.routers.invest.tls=true"
networks:
  proxy:
    external: true