services:
  invest:
    build: .
#    ports:
#      - "8000:8000"
    networks:
      - proxy
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - traefik.enable=true
      - traefik.http.services.invest.loadbalancer.server.port=8000
      - traefik.http.routers.invest.rule=Host(`invest.theroeders.net`)
      - traefik.http.routers.invest.entrypoints=https
      - traefik.http.routers.invest.tls=true
networks:
  proxy:
    external: true